import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "700", "900", "800", "600", "500"],
});

export const metadata: Metadata = {
  title: "student DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: any;
}) {
  return (
    <html
      crxlauncher="">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}